// Package helpermgr implements the server side of the ProxBack node helper
// protocol: single-use enrollment tokens, registration (which learns the
// helper's address from the connection and stores its access secret encrypted),
// hashed API keys and heartbeat based online tracking.
//
// It deliberately mirrors package agentmgr; the two enrollment flows share the
// enroll_tokens table and differ only in purpose.
package helpermgr

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"log/slog"
	"net"
	"net/http"
	"strconv"
	"strings"
	"time"

	"proxback/internal/auth"
	"proxback/internal/store"
)

// OnlineWindow is how recently a helper must have been seen to count as online.
// The helper heartbeats every 30 s, so this tolerates two missed beats.
const OnlineWindow = 90 * time.Second

// Errors returned by the manager.
var (
	ErrUnauthorized = errors.New("helpermgr: unauthorized")
	ErrBadToken     = errors.New("helpermgr: invalid or expired enrollment token")
	// ErrNoHost is returned when a helper enrollment token is minted without a
	// Proxmox host. A helper that does not know its cluster cannot be routed to,
	// so there is no useful token to hand out.
	ErrNoHost = errors.New("helpermgr: an enrollment token needs the Proxmox host the node belongs to")
)

// Manager owns node helper registrations.
type Manager struct {
	st  *store.Store
	log *slog.Logger
	hc  *http.Client
}

// New builds a manager.
func New(st *store.Store, log *slog.Logger) *Manager {
	if log == nil {
		log = slog.Default()
	}
	return &Manager{
		st:  st,
		log: log,
		// Asking a helper to update itself is a short call — it answers as soon
		// as it has decided whether it can — but the helper downloads and
		// verifies its new binary before answering, so the timeout allows for a
		// slow link rather than for a slow decision.
		hc: &http.Client{Timeout: updateRequestTimeout},
	}
}

// CreateEnrollToken issues a single-use helper enrollment token valid for 24
// hours, minted for one Proxmox host. The host travels with the token so the
// registering helper inherits it: the node never has to know, or be told, which
// cluster it belongs to. An unknown or empty host is refused, because the
// resulting registration could not be used to route anything.
func (m *Manager) CreateEnrollToken(ctx context.Context, hostID string) (*store.EnrollToken, error) {
	hostID = strings.TrimSpace(hostID)
	if hostID == "" {
		return nil, ErrNoHost
	}
	if _, err := m.st.PVEHostByID(ctx, hostID); err != nil {
		if errors.Is(err, store.ErrNotFound) {
			return nil, ErrNoHost
		}
		return nil, err
	}
	tok, err := auth.NewEnrollToken()
	if err != nil {
		return nil, err
	}
	return m.st.CreateEnrollToken(ctx, tok, store.EnrollPurposeHelper, hostID, auth.EnrollTokenTTL)
}

// RegisterRequest is the body of POST /api/helpers/register.
type RegisterRequest struct {
	Token string `json:"token"`
	Node  string `json:"node"`
	Port  int    `json:"port"`
	// Version is the helper build version.
	Version string `json:"version"`
	// AccessSecret is generated by the helper and is the bearer token the server
	// presents on every /export and /import call.
	AccessSecret string `json:"accessSecret"`
}

// RegisterResponse is the body returned by POST /api/helpers/register.
type RegisterResponse struct {
	HelperID string `json:"helperId"`
	APIKey   string `json:"apiKey"`
}

// Register consumes a helper enrollment token and stores the registration.
// remoteAddr is the request's RemoteAddr: the helper never tells the server
// where it lives, the connection does.
func (m *Manager) Register(ctx context.Context, req RegisterRequest, remoteAddr string) (*RegisterResponse, error) {
	if req.Token == "" {
		return nil, ErrBadToken
	}
	node := strings.TrimSpace(req.Node)
	if node == "" {
		return nil, errors.New("helpermgr: node is required")
	}
	if req.AccessSecret == "" {
		return nil, errors.New("helpermgr: accessSecret is required")
	}
	// The token names the host, so the registration is bound to (host, node)
	// without the node knowing anything about its cluster.
	tok, err := m.st.ConsumeEnrollTokenFor(ctx, req.Token, store.EnrollPurposeHelper)
	if err != nil {
		if errors.Is(err, store.ErrNotFound) {
			return nil, ErrBadToken
		}
		return nil, err
	}
	if tok.HostID == "" {
		// A token minted before helpers carried a host identity. Refusing it is
		// the safe answer: the alternative is a registration nothing may route to.
		return nil, ErrNoHost
	}
	key, err := auth.NewAgentKey()
	if err != nil {
		return nil, err
	}
	port := req.Port
	if port <= 0 {
		port = store.DefaultHelperPort
	}
	now := store.Now()
	h := &store.NodeHelper{
		HostID:       tok.HostID,
		Node:         node,
		Address:      Address(remoteAddr),
		Port:         port,
		Version:      req.Version,
		AccessSecret: req.AccessSecret,
		APIKeyHash:   auth.HashAgentKey(key),
		LastSeen:     &now,
	}
	if _, err := m.st.CreateHelper(ctx, h); err != nil {
		return nil, err
	}
	m.log.Info("node helper registered", "helperId", h.ID, "hostId", h.HostID, "node", h.Node,
		"address", h.Address, "port", h.Port, "version", h.Version)
	return &RegisterResponse{HelperID: h.ID, APIKey: key}, nil
}

// Address reduces a request RemoteAddr to the host part. Proxy headers are
// deliberately ignored: the helper must be reachable from the server on the
// address it actually connected from.
func Address(remoteAddr string) string {
	if host, _, err := net.SplitHostPort(remoteAddr); err == nil {
		return host
	}
	return remoteAddr
}

// Authenticate resolves a helper from a bearer API key.
func (m *Manager) Authenticate(ctx context.Context, key string) (*store.NodeHelper, error) {
	if key == "" {
		return nil, ErrUnauthorized
	}
	h, err := m.st.HelperByKeyHash(ctx, auth.HashAgentKey(key))
	if err != nil {
		if errors.Is(err, store.ErrNotFound) {
			return nil, ErrUnauthorized
		}
		return nil, err
	}
	return h, nil
}

// HeartbeatRequest is the body of POST /api/helpers/heartbeat. Version is
// optional: a helper old enough not to send it keeps the version it registered
// with, and its heartbeat still counts.
type HeartbeatRequest struct {
	Version string `json:"version,omitempty"`
}

// Heartbeat records liveness and refreshes the helper's reported version.
func (m *Manager) Heartbeat(ctx context.Context, helperID string, req HeartbeatRequest) error {
	return m.st.RecordHelperHeartbeat(ctx, helperID, store.Now(), req.Version)
}

// ---------------------------------------------------------------- self-update

// updateRequestTimeout bounds the call that tells a helper to update itself.
// The helper downloads and verifies the new binary before it answers, so this
// covers a transfer over the management network, not a decision.
const updateRequestTimeout = 10 * time.Minute

// UpdateRequest is the body of POST /update on a node helper.
//
// It names an asset, not a URL: the helper fetches its new binary from the
// server it is enrolled with, using its own stored server address, so nothing
// the server sends can point a node at somewhere else. Sha256 and SizeBytes are
// what the server measured on the file it is about to serve.
type UpdateRequest struct {
	Version   string `json:"version"`
	Asset     string `json:"asset"`
	Sha256    string `json:"sha256"`
	SizeBytes int64  `json:"sizeBytes"`
}

// UpdateResponse is what a helper answers when it has applied an update.
type UpdateResponse struct {
	OK      bool   `json:"ok"`
	Version string `json:"version"`
	// Restarting reports whether the helper is on its way down to come back on
	// the new binary. The server never treats this as proof: only a heartbeat
	// carrying the new version is.
	Restarting bool `json:"restarting"`
}

// ErrHelperBusy is returned when a helper refuses to update because it has an
// export, import or policy script running. Restarting it would abort the run.
var ErrHelperBusy = errors.New("helpermgr: the node helper has work in flight")

// ErrHelperUnreachable marks a failure that never reached the helper at all.
var ErrHelperUnreachable = errors.New("helpermgr: the node helper could not be reached")

// RequestUpdate tells one helper to replace its own binary and restart.
//
// Helpers are contacted directly by the server over their authenticated HTTP
// API — the same channel that already carries export and import — rather than
// polling for work like an agent does, so this is a synchronous call: it
// returns once the helper has downloaded, verified and installed the binary, or
// once it has refused. A successful return still is not a successful update.
// That is only established when the helper heartbeats at the new version.
func (m *Manager) RequestUpdate(ctx context.Context, h *store.NodeHelper, req UpdateRequest) (UpdateResponse, error) {
	var out UpdateResponse
	if h == nil {
		return out, errors.New("helpermgr: no helper")
	}
	port := h.Port
	if port <= 0 {
		port = store.DefaultHelperPort
	}
	target := "http://" + net.JoinHostPort(h.Address, strconv.Itoa(port)) + "/update"
	raw, err := json.Marshal(req)
	if err != nil {
		return out, fmt.Errorf("helpermgr: encode update request: %w", err)
	}
	httpReq, err := http.NewRequestWithContext(ctx, http.MethodPost, target, bytes.NewReader(raw))
	if err != nil {
		return out, fmt.Errorf("helpermgr: build update request: %w", err)
	}
	httpReq.Header.Set("Content-Type", "application/json")
	httpReq.Header.Set("Authorization", "Bearer "+h.AccessSecret)
	resp, err := m.hc.Do(httpReq)
	if err != nil {
		return out, fmt.Errorf("%w at %s: %w", ErrHelperUnreachable, target, err)
	}
	defer resp.Body.Close()
	body, _ := io.ReadAll(io.LimitReader(resp.Body, 64<<10))
	if resp.StatusCode == http.StatusConflict {
		return out, fmt.Errorf("%w: %s", ErrHelperBusy, helperMessage(body))
	}
	if resp.StatusCode < 200 || resp.StatusCode >= 300 {
		return out, fmt.Errorf("helpermgr: node helper %s answered http %d: %s",
			target, resp.StatusCode, helperMessage(body))
	}
	if err := json.Unmarshal(body, &out); err != nil {
		return out, fmt.Errorf("helpermgr: decode update response: %w", err)
	}
	m.log.Info("node helper self-update applied", "helperId", h.ID, "node", h.Node,
		"version", out.Version, "restarting", out.Restarting)
	return out, nil
}

// helperMessage pulls the message out of a helper's {"error": "..."} answer,
// falling back to the raw body so nothing is swallowed.
func helperMessage(body []byte) string {
	var env struct {
		Error string `json:"error"`
	}
	if err := json.Unmarshal(body, &env); err == nil && env.Error != "" {
		return env.Error
	}
	return strings.TrimSpace(string(body))
}

// Online reports whether a helper counts as online.
func Online(h *store.NodeHelper) bool {
	if h == nil || h.LastSeen == nil {
		return false
	}
	return time.Since(*h.LastSeen) <= OnlineWindow
}

// Status returns "unassigned", "online" or "offline" for a helper. A helper
// with no host outranks liveness: it may be heartbeating perfectly and still
// must not be used, because nothing can say which cluster's "pve1" it is.
func Status(h *store.NodeHelper) string {
	if h == nil || h.HostID == "" {
		return store.HelperUnassigned
	}
	if Online(h) {
		return "online"
	}
	return "offline"
}
