// Package helpermgr implements the server side of the ProxBack node helper
// protocol: single-use enrollment tokens, registration (which learns the
// helper's address from the connection and stores its access secret encrypted),
// hashed API keys and heartbeat based online tracking.
//
// It deliberately mirrors package agentmgr; the two enrollment flows share the
// enroll_tokens table and differ only in purpose.
package helpermgr

import (
	"context"
	"errors"
	"log/slog"
	"net"
	"strings"
	"time"

	"proxback/internal/auth"
	"proxback/internal/store"
)

// OnlineWindow is how recently a helper must have been seen to count as online.
// The helper heartbeats every 30 s, so this tolerates two missed beats.
const OnlineWindow = 90 * time.Second

// Errors returned by the manager.
var (
	ErrUnauthorized = errors.New("helpermgr: unauthorized")
	ErrBadToken     = errors.New("helpermgr: invalid or expired enrollment token")
)

// Manager owns node helper registrations.
type Manager struct {
	st  *store.Store
	log *slog.Logger
}

// New builds a manager.
func New(st *store.Store, log *slog.Logger) *Manager {
	if log == nil {
		log = slog.Default()
	}
	return &Manager{st: st, log: log}
}

// CreateEnrollToken issues a single-use helper enrollment token valid for 24 hours.
func (m *Manager) CreateEnrollToken(ctx context.Context) (*store.EnrollToken, error) {
	tok, err := auth.NewEnrollToken()
	if err != nil {
		return nil, err
	}
	return m.st.CreateEnrollToken(ctx, tok, store.EnrollPurposeHelper, auth.EnrollTokenTTL)
}

// RegisterRequest is the body of POST /api/helpers/register.
type RegisterRequest struct {
	Token string `json:"token"`
	Node  string `json:"node"`
	Port  int    `json:"port"`
	// Version is the helper build version.
	Version string `json:"version"`
	// AccessSecret is generated by the helper and is the bearer token the server
	// presents on every /export and /import call.
	AccessSecret string `json:"accessSecret"`
}

// RegisterResponse is the body returned by POST /api/helpers/register.
type RegisterResponse struct {
	HelperID string `json:"helperId"`
	APIKey   string `json:"apiKey"`
}

// Register consumes a helper enrollment token and stores the registration.
// remoteAddr is the request's RemoteAddr: the helper never tells the server
// where it lives, the connection does.
func (m *Manager) Register(ctx context.Context, req RegisterRequest, remoteAddr string) (*RegisterResponse, error) {
	if req.Token == "" {
		return nil, ErrBadToken
	}
	node := strings.TrimSpace(req.Node)
	if node == "" {
		return nil, errors.New("helpermgr: node is required")
	}
	if req.AccessSecret == "" {
		return nil, errors.New("helpermgr: accessSecret is required")
	}
	if err := m.st.ConsumeEnrollToken(ctx, req.Token, store.EnrollPurposeHelper); err != nil {
		if errors.Is(err, store.ErrNotFound) {
			return nil, ErrBadToken
		}
		return nil, err
	}
	key, err := auth.NewAgentKey()
	if err != nil {
		return nil, err
	}
	port := req.Port
	if port <= 0 {
		port = store.DefaultHelperPort
	}
	now := store.Now()
	h := &store.NodeHelper{
		Node:         node,
		Address:      Address(remoteAddr),
		Port:         port,
		Version:      req.Version,
		AccessSecret: req.AccessSecret,
		APIKeyHash:   auth.HashAgentKey(key),
		LastSeen:     &now,
	}
	if _, err := m.st.CreateHelper(ctx, h); err != nil {
		return nil, err
	}
	m.log.Info("node helper registered", "helperId", h.ID, "node", h.Node,
		"address", h.Address, "port", h.Port, "version", h.Version)
	return &RegisterResponse{HelperID: h.ID, APIKey: key}, nil
}

// Address reduces a request RemoteAddr to the host part. Proxy headers are
// deliberately ignored: the helper must be reachable from the server on the
// address it actually connected from.
func Address(remoteAddr string) string {
	if host, _, err := net.SplitHostPort(remoteAddr); err == nil {
		return host
	}
	return remoteAddr
}

// Authenticate resolves a helper from a bearer API key.
func (m *Manager) Authenticate(ctx context.Context, key string) (*store.NodeHelper, error) {
	if key == "" {
		return nil, ErrUnauthorized
	}
	h, err := m.st.HelperByKeyHash(ctx, auth.HashAgentKey(key))
	if err != nil {
		if errors.Is(err, store.ErrNotFound) {
			return nil, ErrUnauthorized
		}
		return nil, err
	}
	return h, nil
}

// Heartbeat records liveness.
func (m *Manager) Heartbeat(ctx context.Context, helperID string) error {
	return m.st.TouchHelper(ctx, helperID, store.Now())
}

// Online reports whether a helper counts as online.
func Online(h *store.NodeHelper) bool {
	if h == nil || h.LastSeen == nil {
		return false
	}
	return time.Since(*h.LastSeen) <= OnlineWindow
}

// Status returns "online" or "offline" for a helper.
func Status(h *store.NodeHelper) string {
	if Online(h) {
		return "online"
	}
	return "offline"
}
